#!/usr/bin/env ruby
require './lib/Api.rb'
require './lib/player.rb'
require './lib/match.rb'
require "highline/import"


singles = ask('Singles?') { |q| q.default = "Y" }
is_singles = (singles =~ /[Yy]/) == 0

players = []
number_of_players = is_singles ? 2 : 4
(1..number_of_players).each_with_index do |index|
	players[index - 1] = new_player index
end

api = Api.new
api.create_game players

match = Match.new api
match.play

puts 'Uploading result to racquet.io ...'
